/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkflowsRouteImport } from './routes/_app.workflows'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppContextRouteImport } from './routes/_app.context'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppWorkflowsIndexRouteImport } from './routes/_app.workflows.index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppContextIndexRouteImport } from './routes/_app.context.index'
import { Route as AppWorkflowsWorkflowIdRouteImport } from './routes/_app.workflows.$workflowId'
import { Route as AppSettingsWorkspaceRouteImport } from './routes/_app.settings.workspace'
import { Route as AppSettingsModelsRouteImport } from './routes/_app.settings.models'
import { Route as AppSettingsMembersRouteImport } from './routes/_app.settings.members'
import { Route as AppSettingsAllowlistRouteImport } from './routes/_app.settings.allowlist'
import { Route as AppSettingsAgentsRouteImport } from './routes/_app.settings.agents'
import { Route as AppContextSkillsSkillIdRouteImport } from './routes/_app.context.skills.$skillId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppContextRoute = AppContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppContextIndexRoute = AppContextIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppContextRoute,
} as any)
const AppWorkflowsWorkflowIdRoute = AppWorkflowsWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => AppWorkflowsRoute,
} as any)
const AppSettingsWorkspaceRoute = AppSettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsModelsRoute = AppSettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAllowlistRoute = AppSettingsAllowlistRouteImport.update({
  id: '/allowlist',
  path: '/allowlist',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAgentsRoute = AppSettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppContextSkillsSkillIdRoute = AppContextSkillsSkillIdRouteImport.update({
  id: '/skills/$skillId',
  path: '/skills/$skillId',
  getParentRoute: () => AppContextRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AppChatRoute
  '/context': typeof AppContextRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/workflows': typeof AppWorkflowsRouteWithChildren
  '/settings/agents': typeof AppSettingsAgentsRoute
  '/settings/allowlist': typeof AppSettingsAllowlistRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/models': typeof AppSettingsModelsRoute
  '/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/context/': typeof AppContextIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/workflows/': typeof AppWorkflowsIndexRoute
  '/context/skills/$skillId': typeof AppContextSkillsSkillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AppChatRoute
  '/settings/agents': typeof AppSettingsAgentsRoute
  '/settings/allowlist': typeof AppSettingsAllowlistRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/models': typeof AppSettingsModelsRoute
  '/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/context': typeof AppContextIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/workflows': typeof AppWorkflowsIndexRoute
  '/context/skills/$skillId': typeof AppContextSkillsSkillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/context': typeof AppContextRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/workflows': typeof AppWorkflowsRouteWithChildren
  '/_app/settings/agents': typeof AppSettingsAgentsRoute
  '/_app/settings/allowlist': typeof AppSettingsAllowlistRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/settings/models': typeof AppSettingsModelsRoute
  '/_app/settings/workspace': typeof AppSettingsWorkspaceRoute
  '/_app/workflows/$workflowId': typeof AppWorkflowsWorkflowIdRoute
  '/_app/context/': typeof AppContextIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/workflows/': typeof AppWorkflowsIndexRoute
  '/_app/context/skills/$skillId': typeof AppContextSkillsSkillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/chat'
    | '/context'
    | '/settings'
    | '/workflows'
    | '/settings/agents'
    | '/settings/allowlist'
    | '/settings/members'
    | '/settings/models'
    | '/settings/workspace'
    | '/workflows/$workflowId'
    | '/context/'
    | '/settings/'
    | '/workflows/'
    | '/context/skills/$skillId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/chat'
    | '/settings/agents'
    | '/settings/allowlist'
    | '/settings/members'
    | '/settings/models'
    | '/settings/workspace'
    | '/workflows/$workflowId'
    | '/context'
    | '/settings'
    | '/workflows'
    | '/context/skills/$skillId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/chat'
    | '/_app/context'
    | '/_app/settings'
    | '/_app/workflows'
    | '/_app/settings/agents'
    | '/_app/settings/allowlist'
    | '/_app/settings/members'
    | '/_app/settings/models'
    | '/_app/settings/workspace'
    | '/_app/workflows/$workflowId'
    | '/_app/context/'
    | '/_app/settings/'
    | '/_app/workflows/'
    | '/_app/context/skills/$skillId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflows': {
      id: '/_app/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/context': {
      id: '/_app/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof AppContextRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workflows/': {
      id: '/_app/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/context/': {
      id: '/_app/context/'
      path: '/'
      fullPath: '/context/'
      preLoaderRoute: typeof AppContextIndexRouteImport
      parentRoute: typeof AppContextRoute
    }
    '/_app/workflows/$workflowId': {
      id: '/_app/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AppWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AppWorkflowsRoute
    }
    '/_app/settings/workspace': {
      id: '/_app/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof AppSettingsWorkspaceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/models': {
      id: '/_app/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof AppSettingsModelsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/allowlist': {
      id: '/_app/settings/allowlist'
      path: '/allowlist'
      fullPath: '/settings/allowlist'
      preLoaderRoute: typeof AppSettingsAllowlistRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/agents': {
      id: '/_app/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof AppSettingsAgentsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/context/skills/$skillId': {
      id: '/_app/context/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/context/skills/$skillId'
      preLoaderRoute: typeof AppContextSkillsSkillIdRouteImport
      parentRoute: typeof AppContextRoute
    }
  }
}

interface AppContextRouteChildren {
  AppContextIndexRoute: typeof AppContextIndexRoute
  AppContextSkillsSkillIdRoute: typeof AppContextSkillsSkillIdRoute
}

const AppContextRouteChildren: AppContextRouteChildren = {
  AppContextIndexRoute: AppContextIndexRoute,
  AppContextSkillsSkillIdRoute: AppContextSkillsSkillIdRoute,
}

const AppContextRouteWithChildren = AppContextRoute._addFileChildren(
  AppContextRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAgentsRoute: typeof AppSettingsAgentsRoute
  AppSettingsAllowlistRoute: typeof AppSettingsAllowlistRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsModelsRoute: typeof AppSettingsModelsRoute
  AppSettingsWorkspaceRoute: typeof AppSettingsWorkspaceRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAgentsRoute: AppSettingsAgentsRoute,
  AppSettingsAllowlistRoute: AppSettingsAllowlistRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsModelsRoute: AppSettingsModelsRoute,
  AppSettingsWorkspaceRoute: AppSettingsWorkspaceRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppWorkflowsRouteChildren {
  AppWorkflowsWorkflowIdRoute: typeof AppWorkflowsWorkflowIdRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
}

const AppWorkflowsRouteChildren: AppWorkflowsRouteChildren = {
  AppWorkflowsWorkflowIdRoute: AppWorkflowsWorkflowIdRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
}

const AppWorkflowsRouteWithChildren = AppWorkflowsRoute._addFileChildren(
  AppWorkflowsRouteChildren,
)

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppContextRoute: typeof AppContextRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppWorkflowsRoute: typeof AppWorkflowsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppContextRoute: AppContextRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppWorkflowsRoute: AppWorkflowsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
