/**
 * The generated Slack outbound helper (agent/lib/slack.ts, emitSlackLib) is
 * the crux of the Slack trigger feature (PLAN correction 3: outbound replies
 * go through the Slack Web API, not eve's Vercel-coupled channel). It is
 * emitted as a standalone, dependency-free module precisely so it can be
 * exercised end-to-end here: we write the EMITTED bytes to disk, import them,
 * and drive `postSlackReply` against a STUB Slack API server (Bun.serve),
 * asserting the real chat.postMessage request shape (auth header, channel,
 * threaded reply) and the failure modes (missing token / channel / Slack
 * error).
 */
import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { emitSlackLib } from "./codegen/libs";

interface CapturedPost {
  authorization: string | null;
  contentType: string | null;
  body: { channel?: string; text?: string; thread_ts?: string };
}

// Load the EMITTED module (not a hand-written copy) so this test guards the
// generated bytes, not a parallel implementation. Its surface mirrors
// emitSlackLib()'s exports.
interface SlackReplyTarget {
  channel: string | null;
  threadTs: string | null;
}
interface PostSlackReplyResult {
  ok: boolean;
  error?: string;
}
interface SlackLib {
  replyTargetFrom(data: Record<string, unknown>): SlackReplyTarget;
  postSlackReply(
    target: SlackReplyTarget,
    text: string,
    options?: { token?: string; apiBaseUrl?: string; fetchImpl?: typeof fetch },
  ): Promise<PostSlackReplyResult>;
}

let lib: SlackLib;
let tmpDir: string;
let stub: ReturnType<typeof Bun.serve>;
const captured: CapturedPost[] = [];
let nextResponse: { ok: boolean; error?: string; status?: number } = { ok: true };

beforeAll(async () => {
  tmpDir = mkdtempSync(join(tmpdir(), "slack-lib-"));
  const file = join(tmpDir, "slack.ts");
  writeFileSync(file, emitSlackLib());
  lib = (await import(file)) as SlackLib;

  stub = Bun.serve({
    port: 0,
    idleTimeout: 0,
    async fetch(req) {
      const url = new URL(req.url);
      if (url.pathname === "/chat.postMessage" && req.method === "POST") {
        const body = (await req.json()) as CapturedPost["body"];
        captured.push({
          authorization: req.headers.get("authorization"),
          contentType: req.headers.get("content-type"),
          body,
        });
        return Response.json(
          nextResponse.ok ? { ok: true } : { ok: false, error: nextResponse.error },
          { status: nextResponse.status ?? 200 },
        );
      }
      return new Response("not found", { status: 404 });
    },
  });
});

afterAll(() => {
  stub?.stop(true);
  rmSync(tmpDir, { recursive: true, force: true });
});

function stubBaseUrl(): string {
  return `http://localhost:${stub.port}`;
}

describe("emitted agent/lib/slack.ts — postSlackReply", () => {
  test("replyTargetFrom reads channel + thread_ts (falls back to ts)", () => {
    expect(lib.replyTargetFrom({ channel: "C1", thread_ts: "1.0", ts: "2.0" })).toEqual({
      channel: "C1",
      threadTs: "1.0",
    });
    expect(lib.replyTargetFrom({ channel: "C1", ts: "2.0" })).toEqual({
      channel: "C1",
      threadTs: "2.0",
    });
    expect(lib.replyTargetFrom({})).toEqual({ channel: null, threadTs: null });
  });

  test("posts a THREADED chat.postMessage with the bot token", async () => {
    captured.length = 0;
    nextResponse = { ok: true };
    const result = await lib.postSlackReply(
      { channel: "C0123", threadTs: "1720000000.000100" },
      "here is your answer",
      { token: "xoxb-test-token", apiBaseUrl: stubBaseUrl() },
    );
    expect(result.ok).toBe(true);
    expect(captured).toHaveLength(1);
    expect(captured[0]!.authorization).toBe("Bearer xoxb-test-token");
    expect(captured[0]!.contentType).toContain("application/json");
    expect(captured[0]!.body).toEqual({
      channel: "C0123",
      text: "here is your answer",
      thread_ts: "1720000000.000100",
    });
  });

  test("omits thread_ts when the target has no thread", async () => {
    captured.length = 0;
    nextResponse = { ok: true };
    await lib.postSlackReply({ channel: "C9", threadTs: null }, "top-level", {
      token: "xoxb-x",
      apiBaseUrl: stubBaseUrl(),
    });
    expect(captured[0]!.body).toEqual({ channel: "C9", text: "top-level" });
    expect("thread_ts" in captured[0]!.body).toBe(false);
  });

  test("reads SLACK_BOT_TOKEN / SLACK_API_BASE_URL from env when options omitted", async () => {
    captured.length = 0;
    nextResponse = { ok: true };
    const prevToken = process.env.SLACK_BOT_TOKEN;
    const prevBase = process.env.SLACK_API_BASE_URL;
    process.env.SLACK_BOT_TOKEN = "xoxb-from-env";
    process.env.SLACK_API_BASE_URL = stubBaseUrl();
    try {
      const result = await lib.postSlackReply({ channel: "C2", threadTs: null }, "env path");
      expect(result.ok).toBe(true);
      expect(captured[0]!.authorization).toBe("Bearer xoxb-from-env");
    } finally {
      if (prevToken === undefined) delete process.env.SLACK_BOT_TOKEN;
      else process.env.SLACK_BOT_TOKEN = prevToken;
      if (prevBase === undefined) delete process.env.SLACK_API_BASE_URL;
      else process.env.SLACK_API_BASE_URL = prevBase;
    }
  });

  test("no token → { ok: false, missing_token }, never calls Slack", async () => {
    captured.length = 0;
    const prev = process.env.SLACK_BOT_TOKEN;
    delete process.env.SLACK_BOT_TOKEN;
    try {
      const result = await lib.postSlackReply({ channel: "C1", threadTs: null }, "x", {
        apiBaseUrl: stubBaseUrl(),
      });
      expect(result).toEqual({ ok: false, error: "missing_token" });
      expect(captured).toHaveLength(0);
    } finally {
      if (prev !== undefined) process.env.SLACK_BOT_TOKEN = prev;
    }
  });

  test("no channel → { ok: false, missing_channel }, never calls Slack", async () => {
    captured.length = 0;
    const result = await lib.postSlackReply({ channel: null, threadTs: null }, "x", {
      token: "xoxb-x",
      apiBaseUrl: stubBaseUrl(),
    });
    expect(result).toEqual({ ok: false, error: "missing_channel" });
    expect(captured).toHaveLength(0);
  });

  test("Slack error response surfaces as { ok: false, <error> }", async () => {
    captured.length = 0;
    nextResponse = { ok: false, error: "channel_not_found" };
    const result = await lib.postSlackReply({ channel: "CX", threadTs: null }, "x", {
      token: "xoxb-x",
      apiBaseUrl: stubBaseUrl(),
    });
    expect(result).toEqual({ ok: false, error: "channel_not_found" });
  });
});
